{"trial_id": "0", "hyperparameters": {"space": [{"class_name": "Float", "config": {"name": "dropout_1", "default": 0.1, "conditions": [], "min_value": 0.1, "max_value": 0.3, "step": 0.1, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "recurrent_dropout_1", "default": 0.1, "conditions": [], "min_value": 0.1, "max_value": 0.3, "step": 0.1, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "dropout_2", "default": 0.1, "conditions": [], "min_value": 0.1, "max_value": 0.3, "step": 0.1, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "recurrent_dropout_2", "default": 0.1, "conditions": [], "min_value": 0.1, "max_value": 0.3, "step": 0.1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "dense_units", "default": null, "conditions": [], "min_value": 32, "max_value": 128, "step": 32, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "dropout_dense", "default": 0.1, "conditions": [], "min_value": 0.1, "max_value": 0.3, "step": 0.1, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "optimizer", "default": "adam", "conditions": [], "values": ["adam", "rmsprop"], "ordered": false}}], "values": {"dropout_1": 0.2, "recurrent_dropout_1": 0.1, "dropout_2": 0.2, "recurrent_dropout_2": 0.1, "dense_units": 128, "dropout_dense": 0.1, "optimizer": "rmsprop"}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"c:\\Users\\14cut\\miniconda\\envs\\gpu_env3\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\14cut\\miniconda\\envs\\gpu_env3\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\14cut\\miniconda\\envs\\gpu_env3\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"c:\\Users\\14cut\\miniconda\\envs\\gpu_env3\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"c:\\Users\\14cut\\miniconda\\envs\\gpu_env3\\lib\\site-packages\\keras_tuner\\src\\engine\\hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n  File \"c:\\Users\\14cut\\miniconda\\envs\\gpu_env3\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"c:\\Users\\14cut\\miniconda\\envs\\gpu_env3\\lib\\site-packages\\tensorflow\\python\\eager\\execute.py\", line 54, in quick_execute\n    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\ntensorflow.python.framework.errors_impl.UnknownError: {{function_node __wrapped__MergeV2Checkpoints_device_/job:localhost/replica:0/task:0/device:CPU:0}} Failed to rename: keras_tuner_english_results\\english_rnn_tuning\\trial_0\\checkpoint_temp/part-00000-of-00001.data-00000-of-00001 to: keras_tuner_english_results\\english_rnn_tuning\\trial_0\\checkpoint.data-00000-of-00001 : Access is denied.\r\n; Input/output error [Op:MergeV2Checkpoints]\n"}